$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
dictionaries: []
dictionaryDefinitions: []
enableFiletypes:
  - go
ignorePaths:
  - .gitignore
  - cspell.config.yaml
ignoreWords: []
import: []
version: "0.2"
words:
  - kkrull
  - Krull
