# Builds and checks
name: Build

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  all-pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - uses: pre-commit/action@v3.0.1

  manuals-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pandoc/actions/setup@main
      with:
        version: 3.2

    - name: Build
      run: make -C man all
