name: Go Build

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  go:
    defaults:
      run:
        working-directory: ./src/go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: src/go/go.sum
          go-version-file: src/go/go.mod

      - run: go version
      - run: go get -t -v .
      - run: make install-tools

  go-build:
    defaults:
      run:
        working-directory: ./src/go
    needs: go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: src/go/go.sum
          go-version-file: src/go/go.mod

      - run: go build -v ./...

  go-test:
    defaults:
      run:
        working-directory: ./src/go
    needs: go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: src/go/go.sum
          go-version-file: src/go/go.mod

      - run: make test-coverage
      - uses: actions/upload-artifact@v4
        with:
          name: test-coverage-go
          path: src/go/coverage.html
